services:
  back:
    environment:
      - PORT=${PORT}
      - DBNAME=${DBNAME}
      - PASSWORD=${PASSWORD}
      - DIALECT=${DIALECT}
      - USER=${USER}
      - HOST=${HOST}
    build:
      context: ./Back
    ports:
      - ${PORT}:${PORT}
    networks:
      - app-network
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    networks:
      - app-network

  front:
    build:
      context: ./Front
    ports:
      - 8080:5173
    networks:
      - app-network

networks:
  app-network:
